### ISSUE TITLE
case statement no break

### ISSUE THREAD

**Issue by rootgrandfather** [jensyt/imurmurhash-js#3]
case 0: k1 ^= len > i ? (key.charCodeAt(i++) & 0xffff) : 0;
case 1: k1 ^= len > i ? (key.charCodeAt(i++) & 0xffff) << 8 : 0;

**Comment by jensyt** [comment]
This behavior is intentional. The case statements are designed to fall through.

**Comment by rootgrandfather** [comment]
All right
